apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    name: myPod
    type: proxys
spec: 
  containers:
  - name: nginxcontainer
    image: nginx:latest
    resources: 
      limits: 
        memory: "128Mi"
        cpu: "500m"
    ports: 
      - containerPort: 80